name: task_pro
description: "Task Manager App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  flutter_screenutil: ^5.9.1
  flutter_bloc: ^8.1.5
  flex_color_scheme: ^7.3.1
  smooth_page_indicator: ^1.1.0
  flutter_slidable: ^3.1.0
  shared_preferences: ^2.2.3
  animated_text_kit: ^4.2.2
  flutter_easyloading: ^3.0.5
  http: ^1.2.0
  shimmer: ^3.0.0
  internet_connection_checker_plus: ^2.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
